import { Baloo_2 } from "next/font/google";
import "./globals.scss";
import styles from "./page.module.css";

import CustomProvider from "@/lib/provider";
import Header from "@/components/header.js";
import LoginDialog from "@/components/LoginDialog.js";

const inter = Baloo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CustomProvider>
        <body className={inter.className}>
          <main className={styles.main}>
            <Header />
            {children}
            <LoginDialog />
          </main>
        </body>
      </CustomProvider>
    </html>
  );
}
